---
title: "Subset RF and DL comparison"
format: html
editor: visual
---

```{r}
#| label: setup
#| message: false

library(terra)
library(sf) 
library(tidyverse)
library(tidymodels)
library(bundle)
library(vip)
library(here)
here()
set.seed(12)
```
### Objective: Subset a small area from current NYS wetland mapping and train both a Random Forest and CNN to compare and evaluate


Import predictor stack raster then subset an area

```{r}
#| eval: false
predstack <- rast(here("Data/Predictor_Stacks/cluster_208_huc_041402011002_raster_predictors.tif"))
subvect <- vect(ext(395000, 397600, 4709000, 4712000), crs = crs(predstack))

substack <- crop(predstack, subvect)
substackDL <- substack[[c("DEM", "r", "g", "b", "nir")]]

writeRaster(substack, here("Data/RF_DL_comp/rasters/substack.tif"), overwrite = TRUE)
writeRaster(substackDL, here("Data/RF_DL_comp/rasters/substack_DL.tif"), overwrite = TRUE)
```

```{r}
substack <- rast(here("Data/RF_DL_comp/rasters/substack.tif"))
substackDL <- rast(here("Data/RF_DL_comp/rasters/substack_DL.tif"))
```


```{r}
plotRGB(substackDL[[c("r", "g", "b")]])
```


Get NWI polygons and create training data

```{r}
#| eval: false
nwi <- vect(here("Data/NWI/NY_NWI_6347.gpkg"))
nwi_subset <- crop(nwi, subvect) |> 
        tidyterra::filter(!str_detect(ATTRIBUTE, "L1|R1|R4|R5")) |> # remove big lake and small streams (unreliable)
        tidyterra::filter(!str_detect(WETLAND_TY, "Marine|Estuarine|Other")) |> # remove marine/estuarine
      tidyterra::mutate(WetClass = case_when(
          str_detect(ATTRIBUTE, "L2|PUB|PUS|PAB|R2|R3") & !str_detect(ATTRIBUTE, "PFO|PEM|PSS") ~ "OWW",
          str_detect(ATTRIBUTE, "PSS") & !str_detect(ATTRIBUTE, "PFO|PEM") ~ "SSW",
          str_detect(ATTRIBUTE, "PEM") & !str_detect(ATTRIBUTE, "PFO|PSS") ~ "EMW",
          str_detect(ATTRIBUTE, "PFO") & !str_detect(ATTRIBUTE, "PSS|PEM") ~ "FSW",
          str_detect(ATTRIBUTE, "PSS") & str_detect(ATTRIBUTE, "PFO") ~ "FSW",
          str_detect(ATTRIBUTE, "PSS") & str_detect(ATTRIBUTE, "PEM") ~ "EMW",
          .default = ATTRIBUTE
          ))
nwi_subset_rast <- rasterize(x = nwi_subset, y = substackDL, 
                             field = "WetClass", 
                             touches = TRUE,
                             filename = here("Data/RF_DL_comp/rasters/nwi_subset_rast.tif"),
                             overwrite = TRUE)

pts <- vect(here("Data/Training_Data/cluster_208_training_pts.gpkg"))
pts_subset <- crop(pts, subvect) |> 
    terra::extract(x = substack, method = "bilinear", bind = TRUE)

train_size <- floor(0.70*nrow(pts_subset))
train_ind <- sample(seq_along(1:nrow(pts_subset)), size = train_size)
train_pts <- pts_subset[train_ind,]
test_pts <- pts_subset[-train_ind,]

pts_subset |> as_tibble() |> group_by(MOD_CLASS) |> summarise(n = n())
train_pts |> as_tibble() |> group_by(MOD_CLASS) |> summarise(n = n())
test_pts |> as_tibble() |> group_by(MOD_CLASS) |> summarise(n = n())

writeVector(nwi_subset, here("Data/RF_DL_comp/vectors/nwi_subset.gpkg"), overwrite = TRUE)
writeVector(pts_subset, here("Data/RF_DL_comp/vectors/nwi_pts_subset.gpkg"), overwrite = TRUE)
writeVector(train_pts, here("Data/RF_DL_comp/vectors/nwi_train_pts_subset.gpkg"), overwrite = TRUE)
writeVector(test_pts, here("Data/RF_DL_comp/vectors/nwi_test_pts_subset.gpkg"), overwrite = TRUE)

```



```{r}
nwi_subset <- vect(here("Data/RF_DL_comp/vectors/nwi_subset.gpkg"))
pts_subset <- vect(here("Data/RF_DL_comp/vectors/nwi_pts_subset.gpkg"))
train_pts <- vect(here("Data/RF_DL_comp/vectors/nwi_train_pts_subset.gpkg"))
test_pts <- vect(here("Data/RF_DL_comp/vectors/nwi_test_pts_subset.gpkg"))

plotRGB(substackDL[[c("r", "g", "b")]])
plot(nwi_subset, "WETLAND_TY", add = TRUE)
plot(pts_subset, "MOD_CLASS", add = TRUE)
```


Train a random forest model within this area 
- separate training and testing data

```{r}
train_data <- as_tibble(train_pts) |> mutate(COARSE_CLASS = as.factor(COARSE_CLASS),
                                             MOD_CLASS = as.factor(MOD_CLASS))
test_data <- as_tibble(test_pts) |> mutate(COARSE_CLASS = as.factor(COARSE_CLASS),
                                             MOD_CLASS = as.factor(MOD_CLASS))

Wetland_Multi_Recipe <- 
    recipe(MOD_CLASS ~ ., data = train_data |> select(-COARSE_CLASS)) 
Wetland_Coarse_Recipe <- 
    recipe(COARSE_CLASS ~ ., data = train_data |> select(-MOD_CLASS)) 


RFM <- 
    rand_forest(
        mtry = ncol(train_data)-2,
        trees = 500,
        min_n = 5
    ) |> 
    set_engine(
        "ranger", 
        num.threads = 24,
        seed = 11,
        importance = "permutation"
        #probability = TRUE
        ) |> 
    set_mode("classification") 

RFM_multi_workflow <- 
    workflow() |> 
    add_model(RFM) |> 
    add_recipe(Wetland_Multi_Recipe)
RFM_coarse_workflow <- 
    workflow() |> 
    add_model(RFM) |> 
    add_recipe(Wetland_Coarse_Recipe)

system.time({RFM_multi_fit <- 
    RFM_multi_workflow |>
    fit(train_data |> select(-COARSE_CLASS))})
system.time({RFM_coarse_fit <- 
    RFM_coarse_workflow |>
    fit(train_data|> select(-MOD_CLASS))})

saveRDS(bundle(RFM_multi_fit), here("Data/RF_DL_comp/models/RFM_Multi_Subset.rds"))
saveRDS(bundle(RFM_coarse_fit), here("Data/RF_DL_comp/models/RFM_Coarse_Subset.rds"))
```

```{r}
RFM_multi_fit |> 
    extract_fit_parsnip() |> 
    vip(num_features = 10) + 
    ggtitle("MultiClass") +
    theme_minimal()
RFM_coarse_fit |> 
    extract_fit_parsnip() |> 
    vip(num_features = 10) + 
    ggtitle("CoarseClass") +
    theme_minimal()

Wetland_MultiTest_Fit <- 
    augment(RFM_multi_fit, test_data)
Wetland_CoarseTest_Fit <- 
    augment(RFM_coarse_fit, test_data)
```

```{r}
cmMulti <- conf_mat(data = Wetland_MultiTest_Fit, truth = MOD_CLASS, estimate = .pred_class) 
cmCoarse <- conf_mat(data = Wetland_CoarseTest_Fit, truth = COARSE_CLASS, estimate = .pred_class) 

cmMulti
cmCoarse

cmMulti |> summary()
cmCoarse |> summary()
```

Predict a map 
```{r}
#| eval: false

multiclass_pred <- terra::predict(object = substack, model = RFM_multi_fit, type = "prob", filename = here("Data/RF_DL_comp/rasters/multiclass_RFpredict_subset.tif"), overwrite = TRUE)

coarseclass_pred <- terra::predict(object = substack, model = RFM_coarse_fit, type = "prob", filename = here("Data/RF_DL_comp/rasters/coarseclass_RFpredict_subset.tif"), overwrite = TRUE)

```

```{r}
multiclass_pred <- rast(here("Data/RF_DL_comp/rasters/multiclass_RFpredict_subset.tif"))
coarseclass_pred <- rast(here("Data/RF_DL_comp/rasters/coarseclass_RFpredict_subset.tif"))

plotRGB(substackDL[[c("r", "g", "b")]])
plot(multiclass_pred)
plot(coarseclass_pred)
```

```{r}
library(supercells)

s <- supercells(multiclass_pred, k = 50, compactness = 0.2, clean = T, minarea = 100, iter = 10, dist_fun = "jsd")

plotRGB(substackDL[[c("r", "g", "b")]])
# plot(multiclass_pred$.pred_SSW)
lines(vect(s), col = "red")
```

